# Generated by Django 5.1.4 on 2025-01-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'managed': False, 'ordering': ('id',), 'verbose_name_plural': 'Book Lists'},
        ),
    ]
