# Generated by Django 5.1.4 on 2025-01-12 09:23

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_booklist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=264, null=True)),
                ('author', models.TextField(blank=True, max_length=264, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, max_length=264, null=True)),
                ('publisher', models.TextField(blank=True, max_length=264, null=True)),
                ('artist', models.TextField(blank=True, max_length=264, null=True)),
                ('quality', models.TextField(blank=True, max_length=264, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=264, null=True)),
                ('genre', models.TextField(blank=True, max_length=264, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('isbn', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='covers/blank.jpg', upload_to=collection.models.get_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Book Lists 2',
                'db_table': 'collect',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
