# Generated by Django 5.1.4 on 2025-01-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_booklistupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='BookListUpdate',
        ),
    ]
