# Generated by Django 5.1.4 on 2025-01-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_delete_tags_delete_booklistupdate'),
        ('profiles', '0014_tags_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookListTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.booklist')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tags')),
            ],
        ),
    ]
