# Generated by Django 5.1.4 on 2025-01-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_bookadmin_delete_booklist2_alter_booklist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookadmin',
            options={'managed': False, 'ordering': ('id',), 'verbose_name_plural': 'Book Lists 2'},
        ),
        migrations.AlterModelTable(
            name='booklist',
            table='collection_booklist',
        ),
    ]
