# Generated by Django 5.1.4 on 2025-01-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_bookadmin_options_alter_booklist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookadmin',
            table='collection_01',
        ),
    ]
