# Generated by Django 5.1.4 on 2025-01-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_booklisttags'),
        ('profiles', '0014_tags_bookmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookListTags',
            new_name='BookAdminTags',
        ),
        migrations.AlterModelOptions(
            name='bookadmintags',
            options={'ordering': ('tags',), 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='bookadmintags',
            name='booklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.bookadmin'),
        ),
    ]
