# Generated by Django 5.1.4 on 2025-01-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_rename_booklisttags_bookadmintags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAdminTags',
        ),
    ]
