# Generated by Django 5.1.4 on 2025-01-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_bookadmin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booklist',
            table='collection_01',
        ),
    ]
