# Generated by Django 5.1.4 on 2025-01-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_booklist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booklist',
            table='collection_booklist',
        ),
    ]
