# Generated by Django 5.1.4 on 2025-01-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_booklist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookadmin',
            options={'managed': False, 'ordering': ('id',), 'verbose_name_plural': 'Book List 2'},
        ),
        migrations.AlterModelOptions(
            name='booklist',
            options={'managed': False, 'ordering': ('id',), 'verbose_name_plural': 'Book List'},
        ),
    ]
