# Generated by Django 5.1.4 on 2025-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_alter_bookadmin_options_alter_booklist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.TextField(blank=True, max_length=264, null=True)),
                ('publishers', models.IntegerField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, max_length=264, null=True)),
                ('bookmarks', models.TextField(blank=True, max_length=264, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookadmin',
            options={'managed': False, 'ordering': ('id',), 'verbose_name_plural': 'Book Admin'},
        ),
    ]
