# Generated by Django 5.1.4 on 2025-01-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_likes_alter_bookadmin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
