# Generated by Django 5.1.4 on 2025-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_bookmarks_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='publishers',
            field=models.TextField(blank=True, max_length=264, null=True),
        ),
    ]
