# Generated by Django 5.1.4 on 2025-01-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_alter_likes_publishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
