# Generated by Django 5.1.4 on 2025-01-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_bookmarks_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
