# Generated by Django 5.1.4 on 2025-01-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
