# Generated by Django 5.1.4 on 2025-01-12 09:23

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, default='blank.jpg', upload_to=profiles.models.get_upload_path),
        ),
    ]
