# Generated by Django 5.1.4 on 2025-01-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_bookmarks_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
