# Generated by Django 5.1.4 on 2025-01-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_tags_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
